/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicBotStatusRouteImport } from './routes/api/public/bot/status'
import { Route as ApiPublicBotSessionRouteImport } from './routes/api/public/bot/session'
import { Route as ApiPublicBotIncomingRouteImport } from './routes/api/public/bot/incoming'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotStatusRoute = ApiPublicBotStatusRouteImport.update({
  id: '/api/public/bot/status',
  path: '/api/public/bot/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotSessionRoute = ApiPublicBotSessionRouteImport.update({
  id: '/api/public/bot/session',
  path: '/api/public/bot/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotIncomingRoute = ApiPublicBotIncomingRouteImport.update({
  id: '/api/public/bot/incoming',
  path: '/api/public/bot/incoming',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/api/public/bot/incoming': typeof ApiPublicBotIncomingRoute
  '/api/public/bot/session': typeof ApiPublicBotSessionRoute
  '/api/public/bot/status': typeof ApiPublicBotStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/api/public/bot/incoming': typeof ApiPublicBotIncomingRoute
  '/api/public/bot/session': typeof ApiPublicBotSessionRoute
  '/api/public/bot/status': typeof ApiPublicBotStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/api/public/bot/incoming': typeof ApiPublicBotIncomingRoute
  '/api/public/bot/session': typeof ApiPublicBotSessionRoute
  '/api/public/bot/status': typeof ApiPublicBotStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/api/public/bot/incoming'
    | '/api/public/bot/session'
    | '/api/public/bot/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/api/public/bot/incoming'
    | '/api/public/bot/session'
    | '/api/public/bot/status'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/api/public/bot/incoming'
    | '/api/public/bot/session'
    | '/api/public/bot/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ApiPublicBotIncomingRoute: typeof ApiPublicBotIncomingRoute
  ApiPublicBotSessionRoute: typeof ApiPublicBotSessionRoute
  ApiPublicBotStatusRoute: typeof ApiPublicBotStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/status': {
      id: '/api/public/bot/status'
      path: '/api/public/bot/status'
      fullPath: '/api/public/bot/status'
      preLoaderRoute: typeof ApiPublicBotStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/session': {
      id: '/api/public/bot/session'
      path: '/api/public/bot/session'
      fullPath: '/api/public/bot/session'
      preLoaderRoute: typeof ApiPublicBotSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/incoming': {
      id: '/api/public/bot/incoming'
      path: '/api/public/bot/incoming'
      fullPath: '/api/public/bot/incoming'
      preLoaderRoute: typeof ApiPublicBotIncomingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ApiPublicBotIncomingRoute: ApiPublicBotIncomingRoute,
  ApiPublicBotSessionRoute: ApiPublicBotSessionRoute,
  ApiPublicBotStatusRoute: ApiPublicBotStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
